# Generated by Django 4.0.3 on 2023-12-12 19:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('func', models.CharField(max_length=255, verbose_name='Функция')),
                ('x_start', models.FloatField(default=0, verbose_name='Начало интервала')),
                ('x_end', models.FloatField(default=0, verbose_name='Конец интервала')),
                ('date_create', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания графика')),
            ],
        ),
    ]
